server:
  port: 8081
grpc:
  server:
    port: ${SERVER_PORT:9090}

spring:
  application:
    name: grpc-server

logging:
  level:
    io.grpc: INFO
    com.taurusx85: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS dd/MM/yyyy} %clr(%-5level) %clr([%thread]){blue} %logger{60} %clr([%X{requestId}]){cyan} --- %msg %n"

